### PR TITLE
Life quality changes  (Added permissons and more)

### PR DESCRIPTION
**Pull request by ImFound**
- Added messages changable via a configuration file (config.yml)
- Renamed DupePluginMain.java to DupePlugin.java
- Renamed dupeCommand.java to DupeCommand.java

Hey, it's conventionally incorrect to put classes with lowercase names and packages with uppercase names.
I made this update, since you are learning java, to help you.

### CODE REVIEW

**Comment by mmvanheusden** [comment]
Yooooo you are so awesome!
thanks for the help!

**Comment by mmvanheusden** [comment]
Hi, the plugin doesn't work anymore on my test server, this is the stacktrace:
```
[15:59:28 ERROR]: Could not load 'plugins\DupePlugin-1.0-SNAPSHOT.jar' in folder 'plugins'
org.bukkit.plugin.InvalidPluginException: Cannot find main class `esp.storage.firstplugin.DupePluginMain'
        at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:73) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:153) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:414) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:322) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_18_R1.CraftServer.loadPlugins(CraftServer.java:422) ~[paper-1.18.1.jar:git-Paper-132]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:285) ~[paper-1.18.1.jar:git-Paper-132]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1202) ~[paper-1.18.1.jar:git-Paper-132]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317) ~[paper-1.18.1.jar:git-Paper-132]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.ClassNotFoundException: esp.storage.firstplugin.DupePluginMain
        at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:151) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:103) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
        at java.lang.Class.forName0(Native Method) ~[?:?]
        at java.lang.Class.forName(Class.java:467) ~[?:?]
        at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:71) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:?]
        ... 8 more
        ```

**Comment by mmvanheusden** [comment]
fixed in commit 4d902f7

**Comment by mmvanheusden** [comment]
Hi, the plugin still seems to be broken. Could you help fixing it?

**Comment by ImFound** [comment]
Okay, i will fix it.

**Comment by ImFound** [comment]
you need to relocate main class on plugin.yml

**Comment by mmvanheusden** [comment]
No, that is already fixed, the issue now is that the plugin wont fill the config file, and thus, output a null error

**Pull request merged**
